# Generated by Django 3.2.8 on 2021-10-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='instrument',
            new_name='name',
        ),
    ]
